language: node_js
node_js:
  - '9'
  - '8'
  - '7.7'
cache:
  directories:
    - $HOME/.npm
    - node_modules
before_script:
  - 'npm prune'
script:
  - npm test
  - npm run bench
after_success:
  - npm run coveralls